org.gradle.jvmargs=-Xmx4G
org.gradle.daemon=true
org.gradle.parallel=true
#org.gradle.configureondemand=true

minecraft_version=1.21.1

# Architectury
architectury_version=13.0.8
enabled_platforms=fabric,neoforge

# Mod
archives_base_name=keymap
maven_group=com.github.einjerjar.mc

mod_version_type = beta
mod_subversion = 1
mod_version = 0.10.2

# Loader Dependencies

fabric_loader_version=0.16.14
fabric_api_version=0.116.0+1.21.1

neoforge_version=21.1.160

# Non MC Dependencies
version_lombok=1.18.32

parchmentmc_version=2024.11.17
